import type { ProgramContent } from "@/lib/programs/types";

// Source: Funding Lab REDIP 2026–27 guide (REDIP 2026–27 Program Guide and Intake 5 FAQ). Re-verify before each intake.
export const redip = {
  slug: "redip",
  name: "Rural Economic Diversification and Infrastructure Program (REDIP)",
  funder: "Province of British Columbia — Rural Programs",
  level: "provincial",
  province: "BC",
  type: "grant",
  summary: "Up to $1M for studies, designs and construction of economic infrastructure that creates jobs and new industry in rural B.C.",
  industries: [],
  stages: ["idea", "preseed", "seed", "growth", "expansion"],
  min_amount: null,
  max_amount: 1_000_000,
  cost_share_pct: 80,
  intake_open: "2026-09-18",
  intake_close: "2026-11-21T07:59:00Z", // Nov 20, 2026 11:59 PM PST
  rolling: false,
  official_url: "https://www2.gov.bc.ca/gov/content/employment-business/economic-development/support-organizations-community-partners/rural-economic-development/redip",
  last_verified_at: "2026-10-04",
  is_featured: true,
  featured_order: 1,
  badge: "B.C. Provincial · Grant",
  headline: "Build in rural B.C. Get up to $1M to do it.",
  subheadline:
    "The Rural Economic Diversification and Infrastructure Program (REDIP), explained in plain language — plus a quick check to see if your project fits.",
  status_text: "Intake 5 closes November 20, 2026, 11:59 PM PST",
  close_at: "2026-11-21T07:59:00Z",
  calculator: "redip",
  official_contact: "RuralDevelopment@gov.bc.ca · 1-250-356-7950",
  disclaimer:
    "Funding Lab is an independent advisor, not part of the Government of B.C. Always confirm with the official program: RuralDevelopment@gov.bc.ca · 1-250-356-7950.",
  content: {
    oneMinute: [
      { title: "Who runs it", body: "The Province of B.C. (Rural Programs). It's a grant, not a loan." },
      { title: "What it does", body: "Pays for studies, designs and construction of economic infrastructure that create jobs and new industry in rural B.C." },
      { title: "What's new", body: "Projects must align with B.C.'s Look West Economic Strategy or a B.C. Major Project. Tariff-hit communities, such as forestry towns, get priority." },
    ],
    keyNumbers: [
      { value: "$1M", label: "Maximum grant per project" },
      { value: "80%", label: "Of eligible costs under $500K (60% at $500K+)" },
      { value: "Nov 20", label: "Intake 5 closes, 11:59 PM PST" },
      { value: "Spring 2027", label: "Funding decisions" },
    ],
    streams: [
      { name: "Development", tag: "Plan it", amount: "Up to $100K · 80% of eligible costs",
        body: "Feasibility studies, business cases, market analysis, engineering design, and environmental and archaeological assessments, so a project can start within 6 months." },
      { name: "Implementation", tag: "Build it", amount: "Up to $1M · 80% under $500K (max $400K), 60% at $500K+ (max $1M)",
        body: "New or improved economic infrastructure, plus equipment for training or business scale-up. Should be shovel-ready." },
      { name: "Community Transition", tag: "Recover", amount: "Case by case · contact the program first",
        body: "For communities losing a major employer, or with an urgent need tied to a B.C. Major Project." },
    ],
    streamsNotes: ["One application, one stream per applicant per intake."],
    qualifies: [
      { heading: "Can lead an application", tone: "yes", items: [
        "Municipalities and regional districts in Rural 1–3 areas",
        "First Nations governments and Indigenous economic development corporations anywhere in B.C.",
        "Not-for-profits with projects in Rural 1–3 areas",
      ] },
      { heading: "Can join as a partner (up to 2)", tone: "info", items: [
        "Businesses, including limited partnerships",
        "Industry organizations",
        "Post-secondary institutions",
        "Community foundations and development corporations",
      ] },
      { heading: "Can't lead", tone: "no", items: [
        "For-profit businesses and limited partnerships",
        "Registered charities",
        "Urban 1–3 communities",
      ] },
    ],
    partnerPath: {
      title: "Partner path for companies",
      steps: [
        "Your company has a job-creating rural project",
        "A rural lead (municipality, regional district, First Nation or non-profit) agrees to apply",
        "Joint application naming you as partner, with a support letter",
        "REDIP covers up to 80%; you and the lead share the rest",
      ],
      conditions: [
        "Broad community benefit",
        "No harm to local competitors",
        "Partner cash and in-kind count toward the lead's 20–40% share",
      ],
    },
    locationCheck:
      "Rural 1–3 areas are eligible, Urban 1–3 are not, and Indigenous communities are always eligible. Check your location with the official REDIP Eligibility Lookup Tool on the program page.",
    sectors: {
      title: "Look West priority sectors",
      chips: ["Trade & Logistics", "Maritime", "AI & Quantum Computing", "Aerospace", "Life Sciences", "Construction Innovation",
        "Agriculture & Food", "Tourism", "Skilled Workers", "Clean Energy", "Critical Minerals & Mining", "Industrial Land", "Defence",
        "A B.C. Major Project in the region"],
      note: "Priority goes to tariff-hit sectors such as forestry.",
    },
    fits: {
      good: ["Logistics warehouse or freight-hub servicing", "Greenhouse or food processing", "Mass-timber or value-added wood equipment",
        "Trades-training equipment", "Solar, wind or transmission", "Industrial-park sewer, grading or drainage", "New tourism features"],
      notFunded: ["Recreation centres, playgrounds, libraries", "Housing or residential servicing", "Roads, sidewalks, residential water and sewer",
        "Fire halls and emergency vehicles", "Mental health or wellness facilities", "Community plans, OCPs, strategic plans", "Routine repairs"],
      rule: "Rule of thumb: if it doesn't clearly drive jobs, business or industry, it won't qualify.",
    },
    calculatorNotes: [
      "In-kind contributions (staff time, space, equipment) can count for up to 10% of the budget at fair market value.",
      "Other B.C. provincial funding doesn't count toward your share.",
      "Cost overruns are yours.",
      "Applications short of the minimum contribution are not assessed.",
    ],
    eligibleCosts: [
      { cost: "Consultants, engineering, design, project management", covered: true },
      { cost: "Construction, materials, utility hookups", covered: true },
      { cost: "Equipment and capital", covered: true, note: "Max 50% of the grant" },
      { cost: "Staff wages for project work", covered: true, note: "Max 25% of the grant" },
      { cost: "Indigenous consultation, marketing, travel at government rates", covered: true },
      { cost: "Land purchase", covered: false },
      { cost: "GST/PST, financing, interest", covered: false },
      { cost: "Legal fees, permits, approvals", covered: false },
      { cost: "Anything spent before approval", covered: false, note: "Don't start early" },
    ],
    howToWin: [
      { title: "Link to Look West", body: "Show how the project grows a Look West priority sector or supports a B.C. Major Project." },
      { title: "Jobs soon", body: "Count the jobs created or retained, and show when they start." },
      { title: "Shovel-ready", body: "Permits, designs and site control in hand, or a clear path to them." },
      { title: "Tariff impact", body: "Explain how the project helps a community hit by U.S. tariffs." },
      { title: "Committed partners", body: "Signed partner letters, not intentions." },
      { title: "Real quotes", body: "Quotes for every major cost, matched line by line to the budget template." },
    ],
    howToWinNote: "REDIP has historically been heavily oversubscribed.",
    keyDates: [
      { date: "Sep 18, 2026", label: "Intake 5 opened" },
      { date: "Now", label: "Register Business BCeID and book a pre-application meeting" },
      { date: "Nov 20, 2026", label: "Intake closes, 11:59 PM PST", body: "Applying early gives no advantage." },
      { date: "Dec 31, 2026", label: "Late council resolutions due", body: "If delayed by the Oct 17 local elections. Past REDIP reports must be done." },
      { date: "Spring 2027", label: "Funding decisions" },
      { date: "After award", label: "Start within 1 year, finish within 2 years" },
    ],
    keyDatesCallout: "Business BCeID can take several weeks. Meet REDIP staff or your Regional Manager before applying.",
    docChecklist: [
      { group: "Everyone", items: ["REDIP budget template (Excel)", "Quotes for all major costs", "Letter from each partner", "Direct deposit form and void cheque", "Business BCeID"] },
      { group: "Building projects", items: ["Permits, assessments and approvals", "KML site map", "Drawings and engineering", "Gantt chart or timeline", "Letters confirming other funding"] },
      { group: "Nice to have", items: ["Business case (ROI, risks, cost-benefit)", "3-year revenue projections", "Timeline for planning projects", "Council or board resolution"] },
    ],
    quickCheck: {
      intro: "Tick every statement that's true for your project.",
      items: [
        { id: "location", label: "The project is in a Rural 1–3 area or an Indigenous community" },
        { id: "lead", label: "An eligible lead will apply (or you are one)" },
        { id: "sector", label: "It grows a Look West sector and creates jobs" },
        { id: "share", label: "You can cover 20% (under $500K) or 40% ($500K+) of costs" },
        { id: "timing", label: "Nothing is spent before approval, and work starts within a year" },
        { id: "type", label: "It is not recreation, housing, roads or emergency services" },
      ],
      bands: [
        { min: 6, max: 6, tone: "strong", title: "Strong fit. Let's build your application.", body: "Book a fit call and we'll map your lead, partners and budget." },
        { min: 4, max: 5, tone: "fixable", title: "Fixable gaps. We'll help close them before Nov 20.", body: "Most gaps are about the lead applicant or cost share. Both are solvable." },
        { min: 0, max: 3, tone: "weak", title: "Probably not REDIP this round.", body: "We'll point you to a better-fit program." },
      ],
    },
    nextSteps: [
      "Send us your quick-check answers",
      "30-minute fit call",
      "Secure your lead applicant and partner letters",
      "Build the application",
      "Submit by Nov 20, and report if funded",
    ],
    officialLinks: [
      { label: "Official REDIP program page", url: "https://www2.gov.bc.ca/gov/content/employment-business/economic-development/support-organizations-community-partners/rural-economic-development/redip" },
    ],
  } satisfies ProgramContent,
};
