import type { ProgramContent } from "@/lib/programs/types";

// Source: Funding Lab RTRI B.C. guide (PacifiCan RTRI pages, FAQ, info deck, Sep 8, 2026 news release, BC Stats), as of October 2026.
export const rtri = {
  slug: "rtri",
  name: "Regional Tariff Response Initiative (RTRI) — British Columbia",
  funder: "Pacific Economic Development Canada (PacifiCan)",
  level: "federal",
  province: "BC",
  type: "contribution",
  summary: "Non-repayable liquidity and pivot funding, plus interest-free repayable loans, for B.C. businesses hit by U.S. tariffs.",
  industries: [],
  stages: ["growth", "expansion", "exit"],
  min_amount: null,
  max_amount: 20_000_000,
  cost_share_pct: 50,
  intake_open: "2025-03-21",
  intake_close: null,
  rolling: true,
  official_url: "https://www.canada.ca/en/pacific-economic-development/services/funding/regional-tariff-response-initiative.html",
  last_verified_at: "2026-10-04",
  is_featured: true,
  featured_order: 2,
  badge: "Federal · PacifiCan · Non-repayable + interest-free repayable",
  headline: "Hit by U.S. tariffs? Get up to $3M you don't repay.",
  subheadline:
    "The Regional Tariff Response Initiative (RTRI) in British Columbia, explained in plain language: the money, the rules, the numbers and how to apply.",
  status_text: "Open now · first come, first served · funding is finite",
  close_at: null,
  calculator: "rtri",
  official_contact: "PacifiCan · 1-888-338-9378",
  disclaimer:
    "Funding Lab is an independent advisor, not part of the Government of Canada or PacifiCan. Always confirm with PacifiCan: 1-888-338-9378.",
  content: {
    heroStats: [
      { value: "$3M", label: "Non-repayable per business" },
      { value: "$20M", label: "Total ceiling incl. repayable" },
      { value: "$3.45B", label: "National RTRI fund" },
      { value: "Open", label: "First come, first served" },
    ],
    whyItMatters: {
      intro: "52.8% of B.C. goods exports went to the U.S. in 2024: $28.7B shipped. The top exports:",
      bars: [
        { label: "Softwood lumber", value: 3.3, display: "$3.3B" },
        { label: "Natural gas", value: 2.4, display: "$2.4B" },
        { label: "Machinery & equipment", value: 2.3, display: "$2.3B" },
        { label: "Petroleum & fuels", value: 2.1, display: "$2.1B" },
        { label: "Agriculture & food", value: 1.9, display: "$1.9B" },
      ],
      note: "Source: BC Stats, 2024 data.",
      facts: [
        "Federal $7.5B package (Aug 25, 2026) adds $1.5B to RTRI; the national fund is $3.45B over 4 years.",
        "B.C. expansion announced Sep 8, 2026 adds liquidity support up to $2M.",
        "PacifiCan since 2021: $708M invested in 783 projects across 177 communities.",
      ],
    },
    oneMinute: [
      { title: "Who runs it", body: "Pacific Economic Development Canada (PacifiCan)." },
      { title: "What it does", body: "Keeps your team paid through the crunch and funds projects that make you more competitive and less reliant on one market." },
      { title: "What's new", body: "Expanded in September 2026 with liquidity support of up to $2M." },
    ],
    keyNumbers: [
      { value: "$3M", label: "Max non-repayable ($2M liquidity + $1M pivot)" },
      { value: "$20M", label: "Max total incl. interest-free repayable" },
      { value: "$1M+", label: "Annual revenue in one of the last two fiscal years" },
      { value: "~90 days", label: "Decision target (business days); claims paid in ~15" },
    ],
    streams: [
      { name: "Liquidity support", tag: "Stay afloat", amount: "Up to $2M non-repayable",
        body: "50% of payroll for up to 12 months. Covers wages plus essential costs (rent, utilities, insurance, property taxes). Liquidity periods end by Mar 31, 2028." },
      { name: "Pivot project", tag: "Adapt", amount: "Up to $1M non-repayable",
        body: "Up to 50% of project costs: productivity, equipment and technology, new markets, supply chains. One non-repayable project per business." },
      { name: "Large pivot project", tag: "Transform", amount: "Over $1M · interest-free repayable",
        body: "Up to 75% of costs. No collateral, no early-repayment penalty. Finish by Mar 31, 2029." },
    ],
    streamsNotes: [
      "Not-for-profits supporting tariff-hit businesses have a separate stream (no liquidity support).",
      "Non-repayable project funding is available once per business; a single project is either repayable or non-repayable.",
      "Other government programs are OK, but not for the same costs.",
    ],
    qualifies: [
      { heading: "Business", tone: "yes", items: ["Incorporated, for-profit, located and operating in B.C."] },
      { heading: "Revenue", tone: "yes", items: ["$1M+ annual revenue in one of the last two fiscal years"] },
      { heading: "Viability", tone: "yes", items: ["Viable before tariffs"] },
      { heading: "Tariff impact (any one)", tone: "yes", items: [
        "In a tariffed sector (Section 232 or other U.S. tariffs), as exporter or supplier",
        "25%+ of revenue from goods ultimately exported to the U.S.",
        "Real damage: big cost increases, supply disruption, lost customers or revenue",
      ] },
      { heading: "Not eligible", tone: "no", items: [
        "No direct or indirect tariff exposure",
        "Businesses started after Mar 21, 2025 are considered case by case",
      ] },
    ],
    pivotExamples: [
      "Boost productivity", "Adopt proven technology (not early-stage R&D)", "Find new markets: Canada, Europe, Asia",
      "Fix supply chains", "Reshore work to B.C.", "Show measurable results with local and regional benefits",
    ],
    calculatorNotes: [
      "Other aid for the same costs reduces liquidity support.",
      "You commit to keep operating and keep staff in Canada.",
      "Pivot projects need at least 10% from non-government sources.",
      "Repayable: 0% interest, 12-month grace after project end, then 60 monthly payments. Late payments bear bank rate + 3%. Final terms are set in your agreement.",
    ],
    proof: {
      counts: ["Bank statements", "Unused lines of credit", "Signed funding letters"],
      doesntCount: ["Forecast revenue", "Receivables", "Promised equity", "SR&ED not yet received"],
    },
    eligibleCosts: [
      { cost: "Wages, rent, utilities, insurance, property taxes", covered: true, note: "Liquidity" },
      { cost: "Project labour and materials", covered: true, note: "New, added costs only" },
      { cost: "Machinery, equipment, infrastructure", covered: true },
      { cost: "Consultants and professional services", covered: true },
      { cost: "Costs to expand or keep markets", covered: true },
      { cost: "Land and buildings", covered: false },
      { cost: "Early-stage R&D (TRL 1–6)", covered: false },
      { cost: "Bonuses, dividends, debt refinancing", covered: false },
      { cost: "Income taxes, GST, vehicles, entertainment", covered: false },
      { cost: "Tariffs and duties, raw materials, inventory", covered: false },
    ],
    howToWin: [
      { title: "Hard tariff evidence", body: "Customs records, supplier notices, export sales data." },
      { title: "Viable before tariffs", body: "Show the business worked before the shock." },
      { title: "Realistic, on-time plan", body: "Milestones you can actually hit." },
      { title: "Matching funds above the minimum", body: "More of your own money gets priority." },
      { title: "Canadian roots", body: "50%+ Canadian-owned, Canadian inputs." },
      { title: "Clear B.C. benefits", body: "Jobs, revenue, exports." },
    ],
    howToWinNote: "Applications are processed in the order received.",
    keyDates: [
      { date: "Mar 21, 2025", label: "Earliest date project costs can count", body: "Costs can go back up to 12 months before your signed application, never before this date." },
      { date: "Aug 22, 2026", label: "Liquidity eligibility period opens" },
      { date: "Now", label: "Apply online — processed in order received" },
      { date: "~90 business days", label: "Decision target" },
      { date: "Mar 31, 2028", label: "Liquidity periods end" },
      { date: "Mar 31, 2029", label: "Pivot projects complete" },
    ],
    keyDatesCallout: "Keep every invoice.",
    docChecklist: [
      { group: "Everyone", items: ["2 years of financial statements (external accountant) plus interim", "Incorporation documents and CRA business number",
        "Tariff evidence (customs records, supplier notices, export sales data)", "List of other government funding", "Signed attestation form"] },
      { group: "Liquidity", items: ["Last 12 months of payroll and CRA remittances", "12-month income and cash-flow forecast", "Proof of cash need",
        "12 months of rent, utilities, insurance, property tax (if claimed)", "Job retention targets"] },
      { group: "Pivot", items: ["Project plan with milestones and budget", "Business plan (tariff impact, edge, team)", "Forecasts for the project + 2 years",
        "Proof of your share", "Quotes and support letters"] },
    ],
    docNote: "Apply through PacifiCan's online portal (stream: BC (PacifiCan) - RTRI-Business). Missing documents mean an incomplete application.",
    quickCheck: {
      intro: "Tick every statement that's true for your business.",
      items: [
        { id: "incorporated", label: "Incorporated for-profit business located and operating in B.C." },
        { id: "revenue", label: "$1M+ revenue in one of the last two fiscal years" },
        { id: "viable", label: "Viable before tariffs" },
        { id: "impact", label: "Can show tariff impact: tariffed sector, 25%+ of revenue from U.S. exports, or real damage" },
      ],
      bands: [
        { min: 4, max: 4, tone: "strong", title: "Strong fit — let's size your liquidity and pivot funding.", body: "Book a fit call and bring your payroll and export numbers." },
        { min: 3, max: 3, tone: "fixable", title: "Possible fit — let's review your tariff evidence.", body: "Most gaps here are about documentation." },
        { min: 0, max: 2, tone: "weak", title: "RTRI may not fit.", body: "We'll point you to a better program." },
      ],
    },
    nextSteps: [
      "Book a free RTRI fit call",
      "30-minute fit call",
      "Pick your mix: liquidity, pivot, or both",
      "Build the file: forecasts, business plan, tariff evidence, attestation",
      "Submit on PacifiCan's portal, then keep up with claims and job reporting",
    ],
    nextStepsCallout: "A complete file sent early beats a perfect one sent late.",
    officialLinks: [
      { label: "PacifiCan RTRI program page", url: "https://www.canada.ca/en/pacific-economic-development/services/funding/regional-tariff-response-initiative.html" },
    ],
  } satisfies ProgramContent,
};
