// 18 sample programs for development (§17). Every row is flagged is_sample and shows
// "Sample data — verify before launch". Amounts are indicative only.
type Sample = {
  slug: string; name: string; funder: string; level: "federal" | "provincial" | "regional";
  province?: string; type: "grant" | "contribution" | "loan" | "tax_credit" | "wage_subsidy" | "equity" | "repayable";
  summary: string; stages: string[]; industries?: string[]; max_amount?: number; cost_share_pct?: number; rolling?: boolean; official_url: string;
};

export const SAMPLE_PROGRAMS: Sample[] = [
  { slug: "irap", name: "Industrial Research Assistance Program (IRAP)", funder: "National Research Council Canada", level: "federal", type: "contribution",
    summary: "Advisory services and non-repayable contributions for technology innovation projects at SMEs.", stages: ["seed", "growth", "expansion"], rolling: true,
    official_url: "https://nrc.canada.ca/en/support-technology-innovation" },
  { slug: "sred", name: "SR&ED Tax Incentive Program", funder: "Canada Revenue Agency", level: "federal", type: "tax_credit",
    summary: "Refundable and non-refundable tax credits for eligible scientific research and experimental development.", stages: ["preseed", "seed", "growth", "expansion"], rolling: true,
    official_url: "https://www.canada.ca/en/revenue-agency/services/scientific-research-experimental-development-tax-incentive-program.html" },
  { slug: "canexport-smes", name: "CanExport SMEs", funder: "Global Affairs Canada", level: "federal", type: "contribution",
    summary: "Cost-share funding for market development activities in new international markets.", stages: ["growth", "expansion"], cost_share_pct: 50,
    official_url: "https://www.tradecommissioner.gc.ca/funding-financement/canexport/sme-pme/index.aspx" },
  { slug: "csbfp", name: "Canada Small Business Financing Program (CSBFP)", funder: "Innovation, Science and Economic Development Canada", level: "federal", type: "loan",
    summary: "Government-backed loans through participating lenders for equipment, leaseholds and real property.", stages: ["seed", "growth", "expansion"], rolling: true,
    official_url: "https://ised-isde.canada.ca/site/canada-small-business-financing-program/en" },
  { slug: "canada-summer-jobs", name: "Canada Summer Jobs", funder: "Employment and Social Development Canada", level: "federal", type: "wage_subsidy",
    summary: "Wage subsidies for employers who create summer jobs for young people aged 15 to 30.", stages: ["idea", "preseed", "seed", "growth", "expansion"],
    official_url: "https://www.canada.ca/en/employment-social-development/services/funding/canada-summer-jobs.html" },
  { slug: "student-work-placement", name: "Student Work Placement Program", funder: "Employment and Social Development Canada", level: "federal", type: "wage_subsidy",
    summary: "Wage subsidies for hiring post-secondary students into work-integrated learning placements.", stages: ["preseed", "seed", "growth", "expansion"], rolling: true,
    official_url: "https://www.canada.ca/en/employment-social-development/programs/student-work-placement.html" },
  { slug: "pacifican-bsp", name: "PacifiCan Business Scale-up and Productivity", funder: "Pacific Economic Development Canada", level: "federal", province: "BC", type: "repayable",
    summary: "Interest-free repayable contributions for B.C. businesses scaling up or adopting technology.", stages: ["growth", "expansion"], rolling: true,
    official_url: "https://www.canada.ca/en/pacific-economic-development/services/funding.html" },
  { slug: "mitacs-accelerate", name: "Mitacs Accelerate", funder: "Mitacs", level: "federal", type: "grant",
    summary: "Co-funded research internships connecting businesses with graduate students and postdocs.", stages: ["seed", "growth", "expansion"], rolling: true,
    official_url: "https://www.mitacs.ca/our-programs/accelerate/" },
  { slug: "futurpreneur-startup", name: "Futurpreneur Start-up Program", funder: "Futurpreneur Canada", level: "federal", type: "loan",
    summary: "Start-up financing and mentorship for entrepreneurs aged 18 to 39.", stages: ["idea", "preseed"], rolling: true,
    official_url: "https://www.futurpreneur.ca/" },
  { slug: "bdc-small-business-loan", name: "BDC Small Business Loan", funder: "Business Development Bank of Canada", level: "federal", type: "loan",
    summary: "Online term loans for working capital and growth projects.", stages: ["seed", "growth", "expansion"], rolling: true,
    official_url: "https://www.bdc.ca/en/financing" },
  { slug: "innovate-bc-ignite", name: "Innovate BC Ignite", funder: "Innovate BC", level: "provincial", province: "BC", type: "grant",
    summary: "Funding for industry-academic partnerships commercializing new technology in B.C.", stages: ["seed", "growth"],
    official_url: "https://www.innovatebc.ca/" },
  { slug: "innovator-skills-initiative", name: "Innovator Skills Initiative", funder: "Innovate BC", level: "provincial", province: "BC", type: "wage_subsidy",
    summary: "Wage support for B.C. businesses hiring in technology and innovation roles.", stages: ["preseed", "seed", "growth"],
    official_url: "https://www.innovatebc.ca/" },
  { slug: "bc-employer-training-grant", name: "B.C. Employer Training Grant", funder: "Province of British Columbia", level: "provincial", province: "BC", type: "grant",
    summary: "Cost-share funding for third-party skills training for current and new employees.", stages: ["seed", "growth", "expansion"], cost_share_pct: 80,
    official_url: "https://www.workbc.ca/" },
  { slug: "bc-interactive-digital-media-tax-credit", name: "B.C. Interactive Digital Media Tax Credit", funder: "Province of British Columbia", level: "provincial", province: "BC", type: "tax_credit",
    summary: "Refundable tax credit on eligible salaries for interactive digital media development.", stages: ["seed", "growth", "expansion"], industries: ["digital_media", "software"], rolling: true,
    official_url: "https://www2.gov.bc.ca/gov/content/taxes/income-taxes/corporate/credits/interactive-digital-media" },
  { slug: "canada-media-fund", name: "Canada Media Fund — Experimental Stream", funder: "Canada Media Fund", level: "federal", type: "contribution",
    summary: "Funding for innovative interactive digital media content and software.", stages: ["preseed", "seed", "growth"], industries: ["digital_media"],
    official_url: "https://cmf-fmc.ca/" },
  { slug: "agri-innovate", name: "AgriInnovate Program", funder: "Agriculture and Agri-Food Canada", level: "federal", type: "repayable",
    summary: "Repayable contributions to commercialize and adopt innovative agri-food technologies.", stages: ["growth", "expansion"], industries: ["agrifood"],
    official_url: "https://agriculture.canada.ca/en/programs/agriinnovate" },
  { slug: "clean-bc-industry-fund", name: "CleanBC Industry Fund", funder: "Province of British Columbia", level: "provincial", province: "BC", type: "contribution",
    summary: "Funding for industrial projects that reduce greenhouse gas emissions.", stages: ["growth", "expansion"], industries: ["cleantech", "advanced_manufacturing"],
    official_url: "https://www2.gov.bc.ca/gov/content/environment/climate-change/industry/cleanbc-industry-fund" },
  { slug: "women-entrepreneurship-loan-fund", name: "Women Entrepreneurship Loan Fund", funder: "Innovation, Science and Economic Development Canada", level: "federal", type: "loan",
    summary: "Loans for women-owned businesses through participating lenders, delivered under the Women Entrepreneurship Strategy.", stages: ["idea", "preseed", "seed", "growth"],
    official_url: "https://ised-isde.canada.ca/site/women-entrepreneurship-strategy/en" },
];
