/**
 * Generates supabase/seed_programs.sql from content/programs/*.ts so featured-grant content
 * lives in one typed place for the initial seed. After launch, admins edit programs in /admin/programs.
 *   npx tsx scripts/gen-seed-programs.ts
 */
import { writeFileSync } from "node:fs";
import { redip } from "../content/programs/redip";
import { rtri } from "../content/programs/rtri";
import { SAMPLE_PROGRAMS } from "../content/programs/sample-programs";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(",")}]::text[]`;
  if (typeof v === "object") return `${q(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const cols = [
  "slug", "name", "funder", "level", "province", "type", "summary", "industries", "stages", "min_amount", "max_amount",
  "cost_share_pct", "intake_open", "intake_close", "rolling", "official_url", "last_verified_at", "is_sample", "is_featured",
  "featured_order", "badge", "headline", "subheadline", "status_text", "close_at", "calculator", "official_contact", "disclaimer", "content",
] as const;

type Row = Partial<Record<(typeof cols)[number], unknown>>;
const rows: Row[] = [
  { ...redip, is_sample: false },
  { ...rtri, is_sample: false },
  ...SAMPLE_PROGRAMS.map((p) => ({
    ...p, industries: p.industries ?? [], province: p.province ?? null, rolling: p.rolling ?? false,
    max_amount: p.max_amount ?? null, cost_share_pct: p.cost_share_pct ?? null, is_sample: true, is_featured: false,
    last_verified_at: null, content: {},
  })),
];

const values = rows.map((r) => `(${cols.map((c) => {
  const v = r[c];
  if ((c === "industries" || c === "stages") && Array.isArray(v) && v.length === 0) return "'{}'::text[]";
  return q(v ?? null);
}).join(", ")})`);

const sql = `-- GENERATED by scripts/gen-seed-programs.ts — do not edit by hand.
-- REDIP and RTRI featured grants (verified 2026-10-04) + 18 sample programs flagged is_sample.
insert into public.programs (${cols.join(", ")}) values
${values.join(",\n")}
on conflict (slug) do nothing;
`;
writeFileSync(new URL("../supabase/seed_programs.sql", import.meta.url), sql);
console.log(`Wrote ${rows.length} programs to supabase/seed_programs.sql`);
